apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: python-sample
spec:
  version: "v1.0.0"
  image: "$REGISTRY-IP:5000/python-helloworld:v1"
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "hello_world"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "main.py"
    srcRepo:
      url: "https://github.com/kmarilleau/openfunction-demo.git"
      sourceSubPath: "sync/python"
      revision: "main"
  serving:
    runtime: knative # default to knative
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    triggers:
      - http:
          port: 80