apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: python-helloworld
spec:
  version: "v1.0.0"
  image: "<docker-username>/python-helloworld:v1" # Replace `<docker-username>` with your Docker Hub username.
  imageCredentials:
    name: dockerhub-credentials
  build:
    builder: "gcr.io/buildpacks/builder"
    env:
      GOOGLE_FUNCTION_TARGET: "hello_world"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "main.py"
      GOOGLE_PYTHON_VERSION: 3.12.1
    srcRepo:
      url: "https://github.com/kmarilleau/openfunction-demo.git"
      sourceSubPath: "sync/python"
      revision: "main"
  serving:
    runtime: knative
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
    triggers:
      - http:
          port: 80